### ISSUE TITLE
Implement memory reading function for macOS

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#1]
- The `src/target.rs` module should be split into platform-dependent implementations.
- Implement memory reading/writing functions for macOS.

**Comment by jrmuizel** [comment]
It's probably best to implement this using debugserver. That's what delve uses to avoid the signing/entitlements problem:
https://github.com/go-delve/delve/blob/95e7cafd0c77790d728a6dc6ffc65c2cb29a13c0/service/debugger/debugger.go#L267
https://github.com/go-delve/delve/blob/80b5b95182bd9101f6f847e2102261ecaec2f23c/pkg/proc/gdbserial/gdbserver.go#L366

**Comment by nbaksalyar** [comment]
> implement this using debugserver

Yes, this will be definitely required, at least for integration with [`rr`](https://rr-project.org/), and there's a crate implementing the GDB serial protocol: [daniel5151/gdbstub](https://github.com/daniel5151/gdbstub), and I think this should be one of the available targets.

However, I think it'd be still useful to have a native macOS target layer that will use `mach_vm_read` and `mach_vm_write`, even taking the code signing inconveniences into account. Delve also uses these to read & write memory, as it seems: https://github.com/go-delve/delve/blob/910f90c3c8274a38bea01c73419dec22902bb5e3/pkg/proc/native/threads_darwin.c#L31-L45

**Comment by bjorn3** [comment]
Implemented by https://github.com/headcrab-rs/headcrab/blob/8e9424a8a9d650a6a0242b0cbbb5f8e7388f9037/src/target/macos/readmem.rs#L44
