### ISSUE TITLE
Rewrite test binary in Rust

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#10]
The [current test binary](https://github.com/headcrab-rs/headcrab/blob/116077cd5d67c2adf7398cd32d56e3a1fd673a94/tests/hello.c) is written in C. It's a temporary measure to simplify working with debug info & predictable variable addresses.

Rewriting the test in Rust will require either disabling [PIE](https://en.wikipedia.org/wiki/Position-independent_code) in compilation flags (`relocation-model=dynamic-no-pic`), or calculating relative addresses (this can be done by calling [`Target::get_addr_range`](https://github.com/headcrab-rs/headcrab/blob/116077cd5d67c2adf7398cd32d56e3a1fd673a94/src/target/linux.rs#L79-L90)) on Linux. MacOS has an undocumented feature to disable ASLR so likely relative addresses calculation won't be required (also see if there's a similar option for Linux).

**Comment by nbaksalyar** [comment]
> see if there's a similar option for Linux

This can be done by calling `personality(ADDR_NO_RANDOMIZE)` (see the [man page](https://man7.org/linux/man-pages/man2/personality.2.html))

**Comment by fabiim** [comment]
I want to have a stab at this. As it is right now I already had to change the test to calculate the absolute address using the ```get_addr_range``` to pass on my linux machine. 

The test was failing even with ASLR disabled (as per instructed [here](https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization) and confirmed working by printing pmap on the test debuggable hello executable multiple times and seeing a constant range of addresses). 

Questions: 

- Can the test calculate an absolute address in all environments? 
- Is it enough if the rust executable under test has a const value ?

**Comment by nbaksalyar** [comment]
>I want to have a stab at this

Thank you!

> already had to change the test to calculate the absolute address using the get_addr_range to pass on my linux machine.

That's interesting. What distribution are you using?

Likely the C compiler has `--enable-default-pie` switched on. Could you please give a try to building the test binary (`hello.c`) with a compiler flag `-no-pie`? You can add it to [Makefile here](https://github.com/headcrab-rs/headcrab/blob/2f086f43a33a74a1170e20522dfa16846e97cbb1/tests/Makefile#L10).

>Can the test calculate an absolute address in all environments?

As in, target platforms? For macOS we can disable ASLR with an [undocumented flag](https://github.com/headcrab-rs/headcrab/blob/2f086f43a33a74a1170e20522dfa16846e97cbb1/Documentation/MacOS.md#address-space-layout-randomization), and we [already do that](https://github.com/headcrab-rs/headcrab/blob/2f086f43a33a74a1170e20522dfa16846e97cbb1/src/target/macos/mod.rs#L49), so it should be fine. The address calculation should be done automatically in the library code, of course, but this will be a separate issue.

> Is it enough if the rust executable under test has a const value ?

It's possible to make it work with `const`, but it would be harder because the value will be just replaced by the compiler and will not included in the debuginfo. You can check it here:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03d9de738ee9573c84a67258dd8cdd2d

if you set the output to LLVM IR and scroll down, you can see there's a debug info generator instruction (`!DIGlobalVariable`) for `HELLO` but not for `HELLO_CONST`.

So probably would be easier with `pub static VAR: &str`.

**Comment by fabiim** [comment]
> That's interesting. What distribution are you using?

Arch

> Likely the C compiler has --enable-default-pie switched on. Could you please give a try to building the test binary (hello.c) with a compiler flag -no-pie? You can add it to Makefile here.
 
Spot on. I don't know if this is desirable, but I went ahead and opened  #23 .   
I don't understand PIE yet, but I will do some reading today on that. 

Thank you for all the guidance on the rust test. That's awesome!  I will start exploring and come back soon.
