### ISSUE TITLE
Integrate readline into the repl example

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#105]
To improve a user's experience, we can use readline in the `repl` example.

Suggested crate: https://github.com/kkawakam/rustyline

**Comment by Stupremee** [comment]
I can do that.

**Comment by bjorn3** [comment]
I already used it: https://github.com/headcrab-rs/headcrab/blob/ab758ff2f5b7d719dfc4c87065d1d76ce720b9aa/Cargo.toml#L41

**Comment by nbaksalyar** [comment]
Huh, weird - I was sure I checked this. :man_facepalming:

**Comment by Stupremee** [comment]
But the integration can be improved very much
