### ISSUE TITLE
Setup CI for macOS

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#16]
Use GitHub Actions or Travis to run continuous integration on macOS.

It's likely that code signing & permissions will be a bit of a problem.

List of resources:
- [lldb documentation on code signing](https://lldb.llvm.org/resources/build.html#code-signing-on-macos)
- [Apple's documentation on code signing](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40005929-CH1-SW1)

**Comment by nbaksalyar** [comment]
> just adding "- osx" as another OS in travis config file should work

That's good spotting, thanks!

The freezing on the integration test is semi-expected - it relies on reading memory of _another_ process as opposed to unit tests, which read memory of their own process, so this is likely caused by insufficient privileges of a parent process.

A short-term solution could be `#[ignore]`ing the integration test for macOS and enabling it for Linux (you can do that with `cargo test -- --ignored`).

If you want to submit a pull request that does that, it'd be very welcome!

**Comment by JJendryka** [comment]
Should be closed by #24
