### ISSUE TITLE
Create a chat room for the community

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#17]
Some of the options are:
- [Gitter](https://gitter.im/)
- [Matrix](https://matrix.org/)
- [Zulip](https://zulipchat.com/)
- All of them? (set up bridges)

**Comment by nbaksalyar** [comment]
Zulip is free & open source and it also supports bridges for IRC and Matrix, so I have created an organisation there:

https://headcrab.zulipchat.com/

**Comment by jrmuizel** [comment]
Looks like joining requires an invitation

**Comment by nbaksalyar** [comment]
Whoops, fixed that. Thanks @jrmuizel!

**Comment by DeltaManiac** [comment]
I accidentally deactivated my account on headcrab.zulip.com😑
@nbaksalyar can you please reactivate it
It's the same one as in GitHub.

**Comment by nbaksalyar** [comment]
@DeltaManiac, sure - just reactivated your account!

**Comment by DeltaManiac** [comment]
@nbaksalyar 
Thanks 😄
