### ISSUE TITLE
Integrate with CirrusCi for BSD target

### ISSUE THREAD

**Issue by DeltaManiac** [headcrab-rs/headcrab#31]
#28 moves *nix based code to a common unix module
This allows us to have separate implementation later for BSD based OS.
The [cirrus.yml](https://github.com/headcrab-rs/headcrab/blob/master/.cirrus.yml) is available but the a few configurations have to be done on the repo/org outlined [here](https://cirrus-ci.org/guide/quick-start/)
After that we can add a badge to [README.md](https://github.com/headcrab-rs/headcrab/blob/master/README.md)

**Comment by nbaksalyar** [comment]
Cirrus CI is now enabled for the repo, thanks!

And I think it should be fine to leave it only at FreeBSD 12, by the way, as there is no reason to support older OSes (same goes for Linux, as we target kernels 3.2+ or probably even 4.0+).

Do you want to raise a PR to disable versions 10 and 11 for now?
