### ISSUE TITLE
Implement WriteMemory routines for macOS

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#35]
Similarly to #7, we should have a memory writing functions for macOS using `mach_vm_write`.

This will require calling [`mach_vm_protect`](https://developer.apple.com/documentation/kernel/1402291-mach_vm_protect?language=objc) for write-protected memory pages.

**Comment by blitzerr** [comment]
@nbaksalyar  Can I work on this ?

**Comment by nbaksalyar** [comment]
@blitzerr, thank you! This should be more-or-less straightforward with macOS, apart from tricky details regarding permissions, so I think implementing this for an own process (i.e. mach_task_self) should be a good start. Also see https://github.com/headcrab-rs/headcrab/pull/41 for a WIP Linux implementation.

**Comment by blitzerr** [comment]
Is this already taken care of by pull #41 ?

**Comment by blitzerr** [comment]
:D you replied before I could press enter

**Comment by nbaksalyar** [comment]
Ah, you’re right, that PR has a work-in-progress implementation for macOS indeed. There are a lot of missing macOS-related functions in the current code though, so more issues need to be created to cover them. I’ll do that shortly.

**Comment by blitzerr** [comment]
@nbaksalyar  So, #41 already takes care of this and nothing more needs to be done here ?

**Comment by bjorn3** [comment]
Looks like it.
