### ISSUE TITLE
Get a list of process threads on Linux

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#36]
`Target::threads() -> &[Thread]` or a similar function should return a view into debuggee process's threads.
For this issue, it should suffice to return a list of thread IDs and thread names (if they're available), so `Thread` can have an API like this:

```rust
trait Thread {
  type ThreadId = usize;

  fn name(&self) -> Option<String>;
  fn thread_id(&self) -> Self::ThreadId;
}
```

Later, more functions can be added to `Thread`.

**Comment by fabiim** [comment]
Working on this. From a quick search I guess I need to parse /proc/[pid]/task or use some crate to do it.

**Comment by nbaksalyar** [comment]
Thanks @fabiim! I suggest to take a look at [`libproc-rs`](https://github.com/andrewdavidmackenzie/libproc-rs) which should implement some of these features for Linux and macOS.
