### ISSUE TITLE
Get current register values for a thread on Linux

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#38]
There should be a function to get the current values of:
- the instruction pointer register (`RIP` on x86_64)
- the stack pointer register (`RSP` on x86_64)
- the stack frame pointer (`RBP` on x86_64)
- general purpose registers (platform-specific, e.g. `RAX`, `RBX`, `RCX` and others on x86_64)

**Comment by bjorn3** [comment]
Working on this. Though currently only for the single-thread case.

**Comment by nbaksalyar** [comment]
Thank you! Single-thread case should be good too :+1:

**Comment by theIDinside** [comment]
Is this issue opened or closed?

**Comment by bjorn3** [comment]
Looks like I implemented this in #40.
