### ISSUE TITLE
Setup continuous integration for Linux

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#4]
Tests require `CAP_SYS_PTRACE`. Find a way to run them for continuous integration, considering that a virtualised environment would probably has this capability disabled.

**Comment by jrmuizel** [comment]
The delve tests: https://github.com/go-delve/delve/blob/67f6a21ab811f8bf4ba50033971752415755f4ed/pkg/proc/proc_test.go see to run fine on travis.

**Comment by nbaksalyar** [comment]
That's interesting, thank you!

It seems that they run builds in Docker with the privileged mode:
https://github.com/go-delve/delve/blob/67f6a21ab811f8bf4ba50033971752415755f4ed/.travis.yml#L65

@kovetskiy also had an idea to try [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for GH Actions, this might be a good solution for the time being.

**Comment by nbaksalyar** [comment]
It does run fine on Travis indeed - thank you! :)
