### ISSUE TITLE
Use PTRACE_O_EXITKILL on Linux

### ISSUE THREAD

**Issue by bjorn3** [headcrab-rs/headcrab#48]
This prevents the tracee from staying alive in a suspended state when the debugger exits.

**Comment by JJendryka** [comment]
I wonder what is the correct behavior when attaching to already running process. I think that it should allow it to continue after debugger exits. This however would require breakpoint cleanup etc when exiting.

**Comment by bjorn3** [comment]
I think there should be different methods for killing the tracee and detaching. I don't know what the preferred behavior in case of a debugger crash would be. Maybe give the user of headcrab the choice when attaching?

**Comment by DeltaManiac** [comment]
> Maybe give the user of headcrab the choice when attaching?
I think this should be the behavior, it should be a choice that the user makes while attaching the debugger.

**Comment by JJendryka** [comment]
PR #62 opened.
