### ISSUE TITLE
Split out code common for all *nix from the Linux target module

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#9]
FreeBSD, OpenBSD, NetBSD, and Illumos/Solaris all use `ptrace(2)` for process control & debuggers. These functions can be shared across `#[cfg(unix)]` OSes.

The main differences are in the way memory is read & written - e.g., FreeBSD supports [`PT_IO` request](https://www.freebsd.org/cgi/man.cgi?query=ptrace) type to write arbitrary amounts of data and Illumos mostly relies on an extended procfs for the same functionality.

**Comment by DeltaManiac** [comment]
I would like to work on this issue. 

So i booted up a freeBSD VM and tried to build and run the test. It however failed with a weird error.

![image](https://user-images.githubusercontent.com/3689561/88014060-a0d45380-cb3b-11ea-97b6-74ae2f4dcf23.png)

This seems weird cause the code works on Ubuntu WSL/CentOs/OpenSuse-Leap without such error.

**Comment by DeltaManiac** [comment]
Further more tried to get it running on Illumos base OpenIndiana and OmniOs. 
Is there anyway we can install rust on a SunOs based system ?  Rustup says we cant.

OmniOs
<img width="864" alt="Screen Shot 2020-07-21 at 10 58 40 AM" src="https://user-images.githubusercontent.com/3689561/88016561-40481500-cb41-11ea-8c73-866937e07b67.png">

OpenIndiana
<img width="802" alt="Screen Shot 2020-07-21 at 10 57 30 AM" src="https://user-images.githubusercontent.com/3689561/88016558-3de5bb00-cb41-11ea-8fb5-6e2a8c73caa6.png">

**Comment by nbaksalyar** [comment]
> I would like to work on this issue.

Thank you!

Adding FreeBSD/Illumos-specific code would be a bit early at this stage (as we'll need to support these platforms in the future), but it would definitely help if we localise Linux-specific code. 

> It however failed with a weird compilation error

I think that's because the `target` module is [conditionally-compiled](https://github.com/headcrab-rs/headcrab/blob/453bad976660c307e7fb8466cc88179a36cc0c2b/src/target/mod.rs#L1-L4) as `#[cfg(target_os = "linux")]`, so on FreeBSD it's not compiled at all. So what we can do instead is the following - a. first, create a separate `target::unix` module and include it in `target/mod.rs` as such:

```rust
#[cfg(unix)]
mod unix;
```

b. move platform-dependent code from `target::linux` there, so we can make a trait for *nix targets, e.g:

```rust
trait UnixTarget {
    /// Launch a new debuggee process.
    pub fn launch(path: &str) -> Result<Target, Box<dyn std::error::Error>> {
        ...
    }
}
```

and because `launch` will use fork & ptrace on _all_ *nix systems, this code can be shared and removed from `target::linux` completely. Then, at later stages, we can start adding new platforms such as the BSD family and others.

And if this new module, `target::unix`, compiles without errors on FreeBSD, we can say that this issue's requirements are met. :)

Hope this makes sense, and please let me know if you need further help!
